server:
  port: 9090

spring:
  application:
    name: FeignProvider

eureka:
  client:
    service-url:
      #向eureka1点发起请求
      defaultZone: http://RhysNi:123456@eureka1.com:7901/eureka/,http://RhysNi:123456@eureka2.com:7902/eureka/,http://RhysNi:123456@eureka3.com:7903/eureka/
  healthcheck:
    enabled: true
  instance:
    #查找主机
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
