server:
  port: 7901

eureka:
  client:
    service-url:
      #向eureka2节点发起请求
      defaultZone: http://RhysNi:123456@eureka2.com:7902/eureka/
    #是否将自己注册到其他Eureka Server,默认为true
    register-with-eureka: true
    #是否从eureka server获取注册信息
    fetch-registry: true
  instance:
    #查找主机
    hostname: eureka1.com
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}



