spring:
  profiles:
    active: eureka1
  application:
    name: EurekaServer
  #安全认证
  security:
    user:
      name: RhysNi
      password: 123456
  boot:
    admin:
      client:
        #Springboot Admin的信息上报地址
        url: http://RhysNi:123456@localhost:9999

eureka:
  server:
    #自我保护机制
    enable-self-preservation: true


#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#server:
#  port: 7901
#
#eureka:
#  client:
#    service-url:
#      #自我注册
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      #是否将自己注册到其他Eureka Server,默认为true
##      register-with-eureka: true
#    #是否从eureka server获取注册信息
#  #    fetch-registry: true
#  instance:
#    #查找主机
#    hostname: eureka1.com



