server:
  port: 6666
# 应用名称
spring:
  application:
    name: GatewayServer
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #可配多条路由规则
      routes:
        - id: feignConsumer1
          #请求过来断定哪些请求可以匹配到uri上，可配多个
          predicates:
            - Path=/feignConsumer/**
            - Query=name,rhys
            - Method=post
#            - Host=www.rhys.vip
#            - Cookie=name,rhys
#            - Weight=FCService,100
          filters:
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              #限流的实现类
              rate-limiter: "#{@customerRateLimiter}"
              #截取哪些规则进入限流算法
              key-resolver: "#{@keyResolver}"
              default-rate-limit.permitsPerSecond: 0.5
              #发放令牌速度1个/s
#              redis-rate-limiter.replenishRate: 1
              #总令牌数量
#              redis-rate-limiter.burstCapacity: 5
          #请求过来路由匹配完成后转发的目标地址
#          uri: http://localhost:9080
          #读取配置时，以"lb://"开头的uri则直接走负载均衡策略
          uri: lb://FeignConsumer1
#        - id: feignConsumer2
          #请求过来断定哪些请求可以匹配到uri上，可配多个
#          predicates:
#            - Path=/feignConsumer/**
#            - Query=name,rhys
#            - Method=post
#            - Host=www.rhys.vip
#            - Cookie=name,rhys
#            - Weight=FCService,5
#          filters:
#          - StripPrefix=1
#          - name: RequestRateLimiter
#            args:
              #截取哪些规则进入限流算法
#              key-resolver: '#{@keyResolver}'
              #发放令牌速度1个/s
#              redis-rate-limiter.replenishRate: 1
              #总令牌数量
#              redis-rate-limiter.burstCapacity: 3
          #请求过来路由匹配完成后转发的目标地址
#          uri: http://localhost:9080
          #读取配置时，以"lb://"开头的uri则直接走负载均衡策略
#          uri: lb://FeignConsumer2


eureka:
  client:
    service-url:
      #向eureka发起注册请求
      defaultZone: http://RhysNi:123456@eureka1.com:7901/eureka/
#      defaultZone: http://RhysNi:123456@eureka1.com:7901/eureka/,http://RhysNi:123456@eureka2.com:7902/eureka/,http://RhysNi:123456@eureka3.com:7903/eureka/
  instance:
    #查找主机
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

FeignConsumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.rhys.gateway.rule.CustomerRule