# 应用名称
spring:
  application:
    name: ZuulServer

server:
  port: 8888

eureka:
  client:
    service-url:
      #向eureka发起注册请求
      defaultZone: http://RhysNi:123456@eureka1.com:7901/eureka/,http://RhysNi:123456@eureka2.com:7902/eureka/,http://RhysNi:123456@eureka3.com:7903/eureka/
  instance:
    #查找主机
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

zuul:
  #根据服务名定义路由
  routes:
    FeignConsumer: /testFC/**
  #请求前缀
  prefix: /api/v1
  #是否带上前缀请求
  strip-prefix: true


