server:
  port: 7777

# 应用名称
spring:
  application:
    name: ConfigCenter
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RhysNi/Config-Center.git
      label: main

eureka:
  client:
    service-url:
      #向eureka发起注册请求
      defaultZone: http://RhysNi:123456@eureka1.com:7901/eureka/,http://RhysNi:123456@eureka2.com:7902/eureka/,http://RhysNi:123456@eureka3.com:7903/eureka/
  instance:
    #查找主机
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

# Actuator Web 访问端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always